server:
    port: 10001 
    context-path: #/liuzh/

logging:
    level:
        com.dos: DEBUG
        com.ibatis: DEBUG

  
spring:
    datasource:
        name: debugtest 
        url: jdbc:mysql://127.0.0.1:3306/uniform_api_db_beta
        username: betauser
        password: betauser
        driver-class-name: com.mysql.jdbc.Driver
