server:
    port: 10001 
    context-path: #/liuzh/

logging:
    level:
        com.dos: DEBUG
        com.ibatis: DEBUG

  
spring:
    datasource:
        name: debugtest 
        url: jdbc:mysql://127.0.0.1:3306/uniform_api_db_dev
        username: devuser
        password: devuser
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        max-idle: 8
        min-idle: 8
        initial-size: 10
